name: uptech_growthbook_sdk_flutter
description: A thin wrapper around GrowthBook's Flutter SDK to support automated testing
version: 0.1.0
homepage: https://github.com/uptech/uptech-growthbook-sdk-flutter

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  growthbook_sdk_flutter: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
