name: uptech_growthbook_sdk_flutter
description: A thin wrapper around GrowthBook's Flutter SDK to support automated testing
version: 1.1.0
homepage: https://github.com/uptech/uptech-growthbook-sdk-flutter

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  growthbook_sdk_flutter: ^3.0.0+0

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
